#!/bin/sh

# This script is provided for backward compatibility with programs
# that use pspell.  Do not use as it will eventually go away.

case $1 in
--version | version)
  echo 0.60.7-20110707
  ;;
--datadir | datadir)
  echo "/usr/local/share"
  ;;
--pkgdatadir | pkgdatadir)
  echo "/usr/local/lib/aspell-0.60"
  ;;
*)
  echo "usage: pspell-config version|datadir|pkgdatadir"
  ;;
esac
